### PR TITLE
Fix off-by-one error.

### PR DESCRIPTION
**Pull request by eliaslevy**

### CODE REVIEW

**Comment by takawitter** [comment]
Thanks @eliaslevy !
I merged your PR.

**Comment by eliaslevy** [comment]
Thanks.  Could you make a new release?

**Comment by takawitter** [comment]
Yes, may be in half day.

**Comment by eliaslevy** [comment]
Thank you.

**Comment by takawitter** [comment]
I made a release :)
http://repo1.maven.org/maven2/com/github/takawitter/trie4j/0.9.8/

**Comment by eliaslevy** [comment]
Thanks!

**Pull request merged**
